// app/disclaimer/page.jsx

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";

import { AlertTriangle, Scale, ShieldCheck } from "lucide-react";

export default function Disclaimer() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-16">

      {/* Hero */}
      <section className="mb-10">
        <h1 className="text-4xl font-bold tracking-tight">
          Legal Disclaimer
        </h1>

        <p className="mt-4 text-muted-foreground max-w-2xl">
          Please read this disclaimer carefully before relying on any analysis
          generated by LegitCheck.
        </p>
      </section>


      <div className="space-y-6">

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Scale className="h-5 w-5 text-primary" />
              Not Legal Advice
            </CardTitle>

            <CardDescription>
              AI-generated insights should not replace professional guidance.
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-3 text-sm text-muted-foreground">
            <p>
              LegitCheck is not a law firm and does not provide legal advice.
            </p>

            <p>
              Analysis reports are generated automatically using artificial
              intelligence and are intended solely for informational purposes.
            </p>

            <p>
              You should consult a qualified attorney before making legal,
              financial, or contractual decisions.
            </p>
          </CardContent>
        </Card>



        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
              AI Limitations
            </CardTitle>
          </CardHeader>

          <CardContent className="space-y-3 text-sm text-muted-foreground">
            <p>
              AI systems may occasionally misunderstand clauses, miss important
              context, or generate incomplete assessments.
            </p>

            <p>
              LegitCheck does not guarantee the accuracy, completeness, or
              suitability of any generated report.
            </p>

            <p>
              Users remain responsible for independently reviewing all
              agreements before signing.
            </p>
          </CardContent>
        </Card>



        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ShieldCheck className="h-5 w-5 text-green-600" />
              Examples of Issues We May Identify
            </CardTitle>
          </CardHeader>

          <CardContent>

            <ul className="space-y-3 text-sm text-muted-foreground list-disc pl-5">
              <li>Broad non-compete obligations</li>

              <li>Unlimited indemnification clauses</li>

              <li>Unilateral termination rights</li>

              <li>Ambiguous payment terms</li>

              <li>Intellectual property ownership concerns</li>

              <li>Liability limitations favoring one party</li>
            </ul>

          </CardContent>
        </Card>



        <Card className="border-red-200 bg-red-50/40">
          <CardContent className="py-5">

            <p className="text-sm font-medium text-red-700">

              No attorney-client relationship is created through the use of
              LegitCheck.

            </p>

          </CardContent>
        </Card>


      </div>



      <div className="mt-10 border-t pt-6">

        <p className="text-xs text-muted-foreground">

          Last updated: June 2026

        </p>

      </div>


    </main>
  );
}